### PR TITLE
Changed annual_rainfall_summaries end point to return metadata and data frame

### PR DESCRIPTION
**Pull request by lloyddewit**

### CODE REVIEW

**Comment by lloyddewit** [comment]
@chrismclarke The `annual_rainfall-summaries` endpoint now returns more sophisticated data (metadata plus data frame). Please could you review and test?

Suggested test data:
```
{
  "country": "zm",
  "station_id": "01122"
}

{
  "country": "zm",
  "station_id": "01122",
  "summaries": [
    "annual_rain", "start_rains", "end_rains"
  ]
}

{
  "country": "zm",
  "station_id": "01122",
  "summaries": [
    "annual_rain"
  ]
}
```
Expected results for the above can be found at:
https://github.com/IDEMSInternational/epicsa-python/tree/main/tests/results_expected

**Comment by lloyddewit** [comment]
@chrismclarke I added 3 additional Python wrappers to `epicsa-python`. I would like to add endpoints for these functions. However, I don't want to do so until you're happy with how this endpoint has been implemented. So I'm a bit stuck and can't proceed.
Do you know when you'll be able to review this PR?
thanks

**Comment by chrismclarke** [comment]
Back from workshops this week, taking a quick look now but receiving the following error locally for the `/v1/annual_summaries_rainfall` endpoint:
```
INFO:     127.0.0.1:56509 - "POST /v1/annual_rainfall_summaries/ HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\middleware\cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\middleware\cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\e-picsa\epicsa-climate-api\app\api\v1\endpoints\annual_rainfall_summaries\router.py", line 24, in get_annual_rainfall_summaries
    result["data"] = get_dataframe_response(result["data"])
                                            ~~~~~~^^^^^^^^
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\pandas\core\frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Apps\e-picsa\epicsa-climate-api\.venv\Lib\site-packages\pandas\core\indexes\base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'data'
```
Are things working correctly for you? Any idea what the error might be? Been a while since I used this API so feeling somewhat rusty

**Comment by lloyddewit** [comment]
@chrismclarke Thank you for trying this.
From the error messages, it looks like the endpoint successfully gets a result from `annual_rainfall_summaries()` but fails when it tries to access the data frame. Specifically, it is looking in the returned dictionary for the key "data" (which is where the data frame is stored) but cannot find this key. So I think that `annual_rainfall_summaries()` is not returning what we expect.
I suspect that you may have an older version of `epicsa-python` installed. Please check that you have the latest `requirements_picsa.txt` (see below).
Then run `pip install --upgrade --no-cache-dir -r requirements_picsa.txt`.
The `--no-cache-dir` is important because otherwise Python just thinks that the cached version is good enough and doesn't install (even though we specify a specific SHA code) - typical sloppy Python.
You may also need to manually uninstall `epicsa-python` first.
If that doesn't work then there's still a big chance that your issue is a dependency problem. You could try uninstalling the R packages and reinstalling them to ensure that you have the latest versions.
Hope this helps.

image

**Comment by lloyddewit** [comment]
@chrismclarke just found my missing comment so I posted it anyway.
Hopetfully this is now OTBE.

**Pull request merged**
