### PR TITLE
Added new wrapper functions

### PR DESCRIPTION
**Pull request by lloyddewit**
@chrismclarke As discussed, please review and merge if OK.
There is a known issue with `crop_success_probabilities()` returning an integer 0 as probability. Some refactoring is also required.
I can resolve these in a seprate PR(s).
Thanks!

### CODE REVIEW

**Comment by chrismclarke** [comment]
Running locally both on my machine and in a docker container I get the following errors 

annual_temperature_summaries
there is no package called ‘forcats’

crop_success_probabilities
unused arguments (water_requirements = list(100, 300, 800), crop_length = list(100, 150), planting_dates = list(90, 100, 110), start_before_season = TRUE)

monthly_temperature_summaries
there is no package called ‘forcats’

season_start_probabilties
AttributeError: module 'epicsawrap' has no attribute 'season_start_probabilities'

Do we need to manually specify forcats in the r package install?... Not sure about the other errors, is everything working for you locally?

**Comment by lloyddewit** [comment]
@chrismclarke 
Thank you for testing. These look like R dependency problems.
The four new `crop_success_probabilities()` arguments were added to `epicsawrap` on 21 June. `season_start_probabilities()` was added on 16 June.

So it looks like your R environment still has an older version of `epicsawrap` installed. Somehow the correct versions of the packages have not been installed:

image


`forcats` is an R package. I checked on my system and I have `forcats` installed in my R environment. 

image

If you upgrade to the latest `epicsawrap` package then the `forcats` package may be installed automatically. If not, we may need to install `forcats` and add instructions to the README.

**Comment by lloyddewit** [comment]
@chrismclarke I just reinstalled everything locally and retested. Everything worked correctly.

**Comment by chrismclarke** [comment]
Down a bit of a deep rabbit-hole on this one, 

**Cause**
R package installation failing silently. 

**Diagnosis** 
Viewing the logs from the R package install script I notice there are various permissions warnings about populating R library files into my default install location (windows programFiles folder), although the script still runs without termination/error

This appears to be an issue on windows when R is installed to a system directory. By default the `devtools::install_github` script seems to install to the system library, which is failing even when running as administrator. Interestingly the standard `install.packages` does not have such issues.

**Solution**
A) Manually install the packages using RStudio which has the option to specify install location (as in your screenshots). The downside to this is the developer would need to remember to manually do this each update (could update docs). Suggested in https://stackoverflow.com/questions/42807247/installing-package-cannot-open-file-permission-denied
 
B) Update the `install_github` to specify the library location for install. This might be nicer, although would need to somehow detect the correct library location automatically otherwise would be hardcoding my own pc path into the common `install_packages_picsa.R` file. Suggested in https://stackoverflow.com/questions/24646065/how-to-specify-lib-directory-when-installing-development-version-r-packages-from

C) Manually add required packages to the `install_packages.R` script. For missing ones like `forcats` this should at least install from the script, however not sure if we will lose any required package version info that would otherwise be populated by the linked repo

D) Use R virtual env. In theory should help ensure consistent R environment within the project, although I've tried this and having a bunch of issues getting [renv(https://github.com/rstudio/renv) to play nice with python's `venv` and abandoning for now. Issue mentioned in https://stackoverflow.com/questions/63708079/errors-like-cons-memory-exhausted-while-import-rpy2, possible solution linked to `https://github.com/rstudio/renv/issues/537`

Not sure if you have any thoughts on this (think it's mostly a windows issue, not entirely sure why it was still failing in docker locally though...)

**Comment by chrismclarke** [comment]
Finally managed to fix with an odd workaround (simply calling `.libPaths()` to output the R library locations before attempting `install_github` appeared to fix). I'm going to add the one-line workaround to this PR as I can't see any way it would harm other installations

Moving forwards I still think we might want to reconsider how R environment is managed as is somewhat user-specific (e.g. the fact you have local packages installed through r-studio). I'm wondering if it would be sensible to have a small `.RProfile` or `.REnviron` that specifies a local location for R packages within the repo itself (added to gitignore)?. This is essentially what is happening with python `.venv` and what `renv` attempts to do (although not working on windows)...

**Comment by chrismclarke** [comment]
As for the endpoints themselves, now working so I think should be good to merge. I noticed the issue with crop probabilities all populating as `0` but will leave that for a follow-up PR to resolve

**Review by chrismclarke — APPROVED** [review]

**Pull request merged**
