### PR TITLE
Reduce the size of the Docker image

### PR DESCRIPTION
**Pull request by istride**
Introduces a multi-stage build, with a builder container that prepares the app dependencies and a 'prod' container that only includes dependencies that are required at runtime.

The size of the final container image is reduced by 60%. Smaller container images reduce resource usage, make deployments faster and reduces the attack surface of the app.

### CODE REVIEW

**Review by ChrisMarsh82 — APPROVED** [review]

**Comment by ChrisMarsh82** [comment]
@istride This is not able to deploy https://github.com/IDEMSInternational/epicsa-climate-api/actions/runs/8876385369
I was going to revert back but currently can't get either dockerfile to work on my machine. I keep getting an issue with entrypoint.sh

**Comment by chrismclarke** [comment]
It does appear that this PR did break the main build and has just never been fixed, I've recently been working on the repo and having the same issues with the entrypoint file.

I've spent an hour or so debugging so far, I'll see if I can get it working again but if not will create a follow-up issue. I appreciate the build is passing but did the app actually run locally in your environment when working on these changes @istride ?

For future ref please also link me into review on any core or large PRs (partly so I can take a look at the technical changes, but moreover just so I can also test on a windows machine). This is particularly useful when refactoring code that I'm the original author of.

**Comment by istride** [comment]
@chrismclarke This was working at the time of the merge. My preference is not to revive old PRs or issues after they've been merged or closed, so I would recommend creating a new issue. I'd be happy to fix it, or provide input.

I have had a brief look into what the problem might be and it seems that uvicorn is no longer being installed in the Docker container. It looks like the recommended way to install fastapi may have changed around the same time this PR was merged. In any case, we need to make sure that uvicorn is installed, either directly (`pip install uvicorn[standard]`), or via fastapi (`pip install fastapi[standard]`).

**Comment by chrismclarke** [comment]
> @chrismclarke This was working at the time of the merge. My preference is not to revive old PRs or issues after they've been merged or closed, so I would recommend creating a new issue. I'd be happy to fix it, or provide input.
> 
> I have had a brief look into what the problem might be and it seems that uvicorn is no longer being installed in the Docker container. It looks like the recommended way to install fastapi may have changed around the same time this PR was merged. In any case, we need to make sure that uvicorn is installed, either directly (`pip install uvicorn[standard]`), or via fastapi (`pip install fastapi[standard]`).

Makes sense, I was just struggling to get my head around when the last actual stable builds where both in CI and my local environments, alongside what the current scope of changes over time might be (e.g. what within our dependencies and CI environments can/are pinned to specific versions vs just inheriting latest properties). It then became significantly more confusing when I looked at the dockerfile and saw it was completely different to last check, and also had some pretty weird behaviours inside it that were making debugging locally more difficult.

I think I managed to get things working at least, so I'll open a PR and tag you to review to see if the changes also make sense to you.

**Pull request merged**
